baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "id"
title = "van.ski | Ivan's Personal Website"
copyright = "Copyright &copy; 2021 - van.ski"
paginate = 8
enableEmoji = true 

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
[params]
    Description = "Catatan kecil Ivan"
    author = "Ivan"

[permalinks]
    blog = ":slug"

[outputs]
    section = ["html", "json"]
    home = ["html", "rss"]

[outputFormats]
    [outputFormats.RSS]
        mediatype = "application/rss"
        baseName = "feed"

rssLimit = 20
