baseURL = "/"
languageCode = "en-us"
title = "Home | van.ski" 
enableEmoji = true

[params]
    Description = "Ivan's little notes"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true 
