baseURL = "/"
languageCode = "en-us"
title = "Home | van.ski" 
paginate = 8
enableEmoji = true
disableHugoGeneratorInject = true 

[params]
    Description = "My Personal Website"
    author = "IceBaby"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

